package com.example.client.utility;

import com.example.client.exceptions.MailException;
import com.example.client.model.ClientModel;
import com.example.common.Email;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.stage.Stage;
import java.io.IOException;

/**
 * A custom ListCell that displays a brief summary of an incoming Email object.
 * It is designed to be generated by a cell factory within a ListView.
 */
public class MailPreviewCell extends ListCell<Email> {
    @FXML
    private Label emailPreview;
    @FXML
    private Label emailSender;
    @FXML
    private Label emailSubject;
    @FXML
    private Button emailDelete;
    @FXML
    Label emailDate;

    private final ClientModel model;
    private Parent fxmlroot;

    public MailPreviewCell(ClientModel model) {
        FXMLLoader loader = new FXMLLoader(MailPreviewCell.class.getResource("/com/example/client/email-preview.fxml"));
        loader.setController(this);
        try {
            fxmlroot = loader.load();
        } catch (IOException e) {
            System.err.println("Could not load MailPreviewCell.fxml : " + e.getMessage());
        }

        this.model = model;

        emailDelete.setOnAction(event -> deleteMail());
        setOnMouseClicked(event -> {
                if (getItem() == null) return;
                model.selectMail(getItem());
                getListView().getSelectionModel().clearSelection(); //removes selection
            });
    }

    @Override
    protected void updateItem(Email item, boolean empty) {
        super.updateItem(item, empty);

        if (empty || item == null) {
            setGraphic(null);
            return;
        }
        emailSender.setText(item.getSender());
        emailSubject.setText(item.getSubject());
        emailPreview.setText(item.getBody().substring(0, Math.min(50, item.getBody().length())));
        emailDate.setText(item.getSentDate());
        setGraphic(fxmlroot); // shows UI graphic
    }

    private void deleteMail() {
        emailDelete.setDisable(true); // Operation allowed once
        new Thread(() -> { // Not daemon, its execution should be blocking to the JVM
            try{
                model.deleteMail(getItem());
                emailDelete.setDisable(false); // Re-enabling to ensure future cells will have it enabled
            }
            catch(MailException e){
                Platform.runLater(()->{ // UI operations run by JavaFX thread
                    emailDelete.setDisable(false); // Re-enabling caused by operation failure
                    try{
                        new PopupManager().showView(new Stage(), "Could not delete mail", e.getMessage(), "ERROR");
                    } catch (IOException ex) {
                        System.err.println("Could not delete mail: " + ex.getMessage());
                    }
                });

            }
        }).start();
    }
}
